#(1)
#from math import *
#print("введите x1")
#x1 = float(input())
#print("введите y1")
#y1 = float(input())
#print("введите x2")
#x2 = float(input())
#print("введите y2")
#y2 = float(input())
#r1= sqrt((x2-x1)**2 + (y2-y1)**2)
#print("Расстояние =", r1)

#2
#print("введите A")
#A = float(input())
#print("введите B")
#B = float(input())
#print("введите C")
#C = float(input())

#AC = abs(C-A)
#BC = abs(C-B)
#cy = (AC+BC)
#print('AC=' ,AC)
#print('BC=' ,BC)
#print('Сумма=', cy)

#3
#print("введите A")
#A = float(input())
#print("введите B")
#B = float(input())
#print("введите C")
#C = float(input())

#AC = abs(A-C)
#BC = abs(C-B)
#p = (AC*BC)
#print('AC=' ,AC)
#print('BC=' ,BC)
#print('Произведение=', p)

#4
#print("введите x1")
#x1 = float(input())
#print("введите y1")
#y1 = float(input())
#print("введите x2")
#x2 = float(input())
#print("введите y2")
#y2 = float(input())

#p = 2*(abs(x1-x2)+abs(y1-y2))
#s = abs(x1-x2)*abs(y1-y2)
#print("Периметр =", p)
#print("Площадь =", s)

#5
import math
print('Введите х1')
x1 = float(input())
print('введите у1')
y1 = float(input())
print('введите х2')
x2 = float(input())
print('введите у2')
y2 = float(input())
print('введите х3')
x3 = float(input())
print('введите у3')
y3 = float(input())
a=(abs(x2-x1))+(abs(y2-y1))
print('a=', a)
b=(abs(x3-x2))+(abs(y3-y2))
print('b=', b)
c=(abs(x1-x3))+(abs(y1-y3))
print('c=', c)
P=(a+b+c)
p1= P/2
print('p1=', p1)
s=(p1*(p1-a)*(p1-b)*(p1-c))
print('s=', s)
st = math.sqrt(s)
print("Их периметр =", P)
print("Их площадь =", st, '(если площадь равна 0, то нет такого треугольника)')

